### PR TITLE
show factorization in history view and improve its display style

### LINKED ISSUE #164: Prime factorization is not displayed in history view
#### Expected behaviour
Prime factorization is displayed in history view

#### Actual behaviour
it isn't

#### Steps to reproduce the behaviour
enable history-view (view->history), enter a number, hit ctrl+f, factorization will not be shown in the history-view widget

#### MATE general version
1.20

#### Package version
master

#### Linux Distribution
debian 10

#### Link to downstream report of your Distribution
none

### PR DESCRIPTION
**Pull request by mbkma**
Shows factorization in history view and shows exponents in factorization instead of repeating the same number.

Test:
before:
1882384 = 2x2x2x2x7x7x7x7x7x7
after:
1882384 = 2^4 x 7^6

Fixes #164

### CODE REVIEW

File: src/math-equation.c [hunk 1]
```diff
@@ -971,6 +971,24 @@ math_equation_set(MathEquation *equation, const gchar *text)
     clear_ans(equation, FALSE);
 }
 
+void
+math_equation_set_with_history(MathEquation *equation, const gchar *text)
```
Comment (rbuj) [inline src/math-equation.c:975]: At first glance the function `math_equation_set_with_history` may be static because it is only used in the math-equation.c file.

**Review by selectiveduplicate — APPROVED** [review]
This looks good to me; runs and works fine on Fedora 32. The display is nicer now and history view works as expected. After resolving the above I think this is good to get merged.

File: src/math-equation.c (hunk 1 above)
Comment (rbuj) [reply src/math-equation.c:975]:
```diff
diff --git a/src/math-equation.c b/src/math-equation.c
index 167e0ec..c739197 100644
--- a/src/math-equation.c
+++ b/src/math-equation.c
@@ -971,7 +971,7 @@ math_equation_set(MathEquation *equation, const gchar *text)
     clear_ans(equation, FALSE);
 }
 
-void
+static void
 math_equation_set_with_history(MathEquation *equation, const gchar *text)
 {
     MathEquationState *state;
diff --git a/src/math-equation.h b/src/math-equation.h
index c62564d..954334c 100644
--- a/src/math-equation.h
+++ b/src/math-equation.h
@@ -108,7 +108,6 @@ void math_equation_redo(MathEquation *equation);
 void math_equation_store(MathEquation *equation, const gchar *name);
 void math_equation_recall(MathEquation *equation, const gchar *name);
 void math_equation_set(MathEquation *equation, const gchar *text);
-void math_equation_set_with_history(MathEquation *equation, const gchar *text);
 void math_equation_set_number(MathEquation *equation, const MPNumber *x);
 void math_equation_insert(MathEquation *equation, const gchar *text);
 void math_equation_insert_digit(MathEquation *equation, guint digit);
```

Comment (mbkma) [reply src/math-equation.c]: @rbuj done

**Review by rbuj — APPROVED** [review]
LGTM
