### PR TITLE
handle multiple consecutive spaces correctly on paste

### LINKED ISSUE #207: Paste figures with spaces should either cut or ignore spaces
#### Expected behaviour
Numbers with spaces as a thousand separator such as `123 456` copied from different sources should not generate errors.
Ideally spaces should be either ignored and preserved or cut making `123 456` -> `123456`

#### Actual behaviour
Numbers with spaces such as `123 456` copied from different sources produce errors "Malformed expression".
When spaces are manually deleted, the program successfully proceeds.

#### Steps to reproduce the behaviour

1. Start `mate-calc`.
2. Copy digits with space as a thousand separator like `123 456`.
3. Paste them in the the program with `Ctrl`-`V`
4. Add `+` `25` `Enter`
5. Confirm error "Malformed expression".

#### MATE general version
1.26.0
1.24.0

#### Package version
```
mate-calc --version
mate-calc 1.26.0
```
```
mate-calc --version
mate-calc 1.24.0
```

#### Linux Distribution
Ubuntu 21.10
Ubuntu 20.04 LTS

### PR DESCRIPTION
**Pull request by mbkma**
fixes #207

### CODE REVIEW

**Review by luigifab — COMMENTED** [review]
Without the PR with french locale with mate-calc 1.26 debian & 1.28 fedora

image

---

Without the PR with c locale with mate-calc 1.26 debian & 1.28 fedora

image

but when I paste the number with the space, I have a warning:

```
fabrice@localhost:~$ LC_ALL=c mate-calc

(process:44337): Gtk-WARNING **: 10:33:38.985: Locale not supported by C library.
	Using the fallback 'C' locale.

(mate-calc:44337): Gtk-WARNING **: 10:34:10.211: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators
```

---

With the PR with french locale it's working by rebuilding Debian 1.26 source package:

image

and with c locale, warning on paste:
```
fabrice@mario:~$ LC_ALL=c mate-calc

(process:7385): Gtk-WARNING **: 10:41:36.675: Locale not supported by C library.
	Using the fallback 'C' locale.

(mate-calc:7385): Gtk-WARNING **: 10:41:37.357: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators
```

**Comment by mbkma** [comment]
these warnings in this pr should also be fixed by https://github.com/mate-desktop/mate-calc/pull/233/commits/4bff62e6ac8ad287f5c3ec6e93974c550e54cb0a

File: src/math-equation.c [hunk 1]
```diff
@@ -803,9 +803,29 @@ math_equation_get_equation(MathEquation *equation)
...
+                while (g_utf8_get_char(g_utf8_next_char(read_iter)) == ' ') {
+                    read_iter = g_utf8_next_char(read_iter);
+                    offset++;
+                }
+                /* Current space will be skipped by not appending it */
+            } else {
+                /* Keep this space - it's not between digits */
+                g_string_append_unichar(eq_text, c);
+            }
+        }
```
Comment (vkareh) [inline src/math-equation.c:828]: I think this entire block can be replaced by just
```c
else if (c == ' ') {
  /* Skip spaces */
}
```
without having to use any of the lookahead logic

Comment (mbkma) [reply src/math-equation.c:828]: No, The current code is specifically designed to skip spaces that act as thousands separators between digits (like "1 000 000") while preserving spaces that have other meanings in the equation (like spaces between operators or function names).
The simplified version would remove ALL spaces from the equation, which could break something like `sin pi`.

**Review by vkareh — APPROVED** [review]
